### ISSUE TITLE
Backspace feature: delete whole word or one character

### ISSUE THREAD

**Issue by cajongonzales** [erichlf/Hemiola#1]
As a user I would like to be able to choose if I delete an entire word or just one character. Possibly backspace and shift backspace? Possibly be able toggle the choices or set a default. This will enable the fast deletion of words and possibly the ability to replace a character to cycle through anagrams.

**Comment by erichlf** [comment]
This is apparently a thing (CTRL + BKSPC backward delete or CTRL + SHIFT + BKSPC forward delete). Based on my testing this is resolved by #22.
