### ISSUE TITLE
Anagram Should Import Words from a Dictionary

### ISSUE THREAD

**Issue by erichlf** [erichlf/Hemiola#5]
Currently Anagram has to be populated manually, but this should be done via a dictionary instead. I think the best option would be to either to send the locale (`std::string`) to the CTOR or a dictionary object to the CTOR.

**Comment by jamesclampffer** [comment]
Not required now but this seems like roughly the right place to handle utf normalization which will simplify everything downstream later on.  Thoughts?

**Comment by erichlf** [comment]
The work for this should be completed in #41

**Comment by erichlf** [comment]
Outdated
